Disable MultiSource/UnitTests/C++11/frame_layout on SPARC
As reported in Issue #57626, `frame_layout.cpp` doesn't compile on SPARC
(both Solaris/sparcv9 and Linux/sparc64):

  FAILED:
MultiSource/UnitTests/C++11/frame_layout/CMakeFiles/frame_layout.dir/frame_layout.cpp.o
  [...]
  fatal error: error in backend: Function
"_Z10test_frameILj4096ELb1ELj2048ELb0ELb0EJEEvDpT4_jPKcP13trace_elementd":
over-aligned dynamic alloca not supported.
  void test_frame<4096u, true, 2048u, false, false>(, unsigned int, char
const*, trace_element*, double)

Therefore, this patch disables the test on SPARC.

Tested on `sparc64-unknown-linux-gnu` (only 3 testsuite failures remaining)
and `sparcv9-sun-solaris2.11` (11 failures once a couple of
Solaris-specific bugs are fixed).

Differential Revision: https://reviews.llvm.org/D133493