Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'
Fix #63072

(cherry picked from commit 87a14216cd4058154fe59a4031e6fb962ebf0462)